CREATE TABLE IF NOT EXISTS patients (
  code_barre VARCHAR(50) NOT NULL,
  nom VARCHAR(100) NOT NULL,
  prenom VARCHAR(100) NOT NULL,
  date_naissance DATE NOT NULL,
  email TEXT NOT NULL,
  age INTEGER NOT NULL,
  tel1 VARCHAR(20) NOT NULL,
  wilaya INTEGER NOT NULL,
  apc INTEGER NOT NULL,
  adresse TEXT NOT NULL,
  dette DOUBLE PRECISION NOT NULL,
  presume SMALLINT NOT NULL,
  sexe SMALLINT NOT NULL,
  type_age SMALLINT NOT NULL,
  conventionne SMALLINT NOT NULL,
  pourc_conv DOUBLE PRECISION NOT NULL,
  lieu_naissance VARCHAR(150) NOT NULL,
  gs INTEGER NOT NULL,
  profession VARCHAR(250) NOT NULL,
  diagnostique VARCHAR(500) NOT NULL,
  tel2 VARCHAR(20) NOT NULL,
  nin TEXT NOT NULL,
  nss TEXT NOT NULL,
  nb_impression INTEGER NOT NULL,
  code_malade VARCHAR(20) NOT NULL,
  photo_url TEXT NOT NULL,
  CONSTRAINT patients_pkey PRIMARY KEY (code_barre)
);
