BEGIN;

ALTER TABLE users_cabinet
  ADD COLUMN IF NOT EXISTS num BIGINT GENERATED BY DEFAULT AS IDENTITY;

-- Ensure every row has a value.
UPDATE users_cabinet
SET num = nextval(pg_get_serial_sequence('users_cabinet', 'num'))
WHERE num IS NULL;

-- Replace existing primary key with num.
DO $$
DECLARE
  r RECORD;
BEGIN
  FOR r IN
    SELECT c.conname
    FROM pg_constraint c
    JOIN pg_class t ON t.oid = c.conrelid
    JOIN pg_namespace n ON n.oid = t.relnamespace
    WHERE n.nspname = current_schema()
      AND t.relname = 'users_cabinet'
      AND c.contype = 'p'
  LOOP
    EXECUTE format('ALTER TABLE users_cabinet DROP CONSTRAINT IF EXISTS %I', r.conname);
  END LOOP;
END $$;

ALTER TABLE users_cabinet
  ALTER COLUMN num SET NOT NULL;

ALTER TABLE users_cabinet
  ADD CONSTRAINT users_cabinet_pkey PRIMARY KEY (num);

COMMIT;
